//torqueRatio is a program that calculates the output torque of a gear
//system given the force applied and size of pinion (driving gear).
//Dec 11, 2020
//B, for metalHp.

#include <stdio.h>
#include <stdlib.h>

void torkRat(double pn, double init, double gr, double *x, double *y, double *z);

void main() {
  double pinion, gear, initialTq; //User inputs.
  double pnTq, grTq, ratio; //Function returns.

  printf("=====================================================\n");
  printf("|           GEAR RATIO AND TORQUE CALCULATOR        |\n");
  printf("=====================================================\n");
  printf("Welcome user! Here you can calculate torque\n");
  printf("generated by a gear system of your input.\n");
  printf("Below, you can specify your variables: \n");
  printf("\n");
  printf("Size of driving gear (addendum radius in meters): ");
  scanf("%lf", &pinion);
  printf("\n");
  printf("Force applied to driving gear (newtons): ");
  scanf("%lf", &initialTq);
  printf("\n");
  printf("Size of driven gear (addendum radius in meters): ");
  scanf("%lf", &gear);
  printf("\n");

  torkRat(pinion, initialTq, gear, &pnTq, &grTq, &ratio);

  printf("=====================================================\n");
  printf("Gear ratio: %.2lf:1\n", ratio);
  printf("Total output torque: %.2lfNm\n", grTq);

}

//Function receives user input and calculates gear radio, output torque.
//Pinion size and gear size are based on addendum radius of each.
//Toruqe output and gear sizes are in Newton-meters and meters respectively.
void torkRat(double pn, double init, double gr,
             double *x, double *y, double *z) {

  *x = pn * init;
  *z = gr / pn;
  *y = (*z) * (*x);
}
