//torqueRatio is a program that calculates the output torque of a gear
//system given the force applied and size of pinion (driving gear).
//Dec 11, 2020
//B, for metalHp.

#include <stdio.h>
#include <stdlib.h>

void torkRat(double pn, double init, double gr, double *x, double *y, double *z);
int powerF(double m, double n);

void main() {
  double pinion, gear, initialTq; //User inputs, pinion is crankshaft.
  double pnTq, grTq, ratio; //Function returns.
  double rpm, power; //Crankshaft speed. Currently for powerF().
  char answer;

  printf("=====================================================\n");
  printf("|           GEAR RATIO AND TORQUE CALCULATOR        |\n");
  printf("=====================================================\n");
  printf("Welcome user! Here you can calculate torque\n");
  printf("generated by a gear system of your input.\n");
  printf("\n");

  printf("Addendum radius of driving gear (meters): ");
  scanf("%lf", &pinion);
  printf("\n");
  printf("Force applied to driving gear (newtons): ");
  scanf("%lf", &initialTq);
  printf("\n");
  printf("Addendum radius of driven gear (meters): ");
  scanf("%lf", &gear);
  printf("\n");

  torkRat(pinion, initialTq, gear, &pnTq, &grTq, &ratio);

  printf("=====================================================\n");
  printf("Gear ratio: %.2lf:1\n", ratio);
  printf("Total output torque: %.2lfNm\n", grTq);
  printf("\n");

  printf("Do you wish to know your engine power output? y/n ");
  scanf(" %c", &answer);

  if(answer == 'y') {
    printf("Engine max rpm: ");
    scanf("%lf", &rpm);
    power = powerF(grTq, rpm);
    printf("Your power output is: %.2lf kW at %.0lf rpm's \n", power, rpm);
  }

  return;
}

//Function receives user input and calculates gear radio, output torque.
//Pinion size and gear size are based on addendum radius of each.
//Toruqe output and gear sizes are in Newton-meters and meters respectively.
void torkRat(double pn, double init, double gr,
             double *x, double *y, double *z) {

  *x = pn * init;
  *z = gr / pn;
  *y = (*z) * (*x);
}

//A function that calculates engine power output.
//Given Torque, and crankshaft speed.
//Units are in metric, imperial later to be implented.
//ALSO, make ssure sober Brandon knows that we need to make this Function
//receive at least 5 variables, each representing the selected gear
//in the transmission. Posibily return an array of RPMs and return a pretty graph
//showing an estimate of what the car's power band would look like in a dyno.
//For this we need a max RPM from user. Dunno, figure it out B!
/* According to wikipedia...
   P = M * n / 9550
   Where P = power (kW)
         M = torque (Nm)
         n = crankshaft speed, also...
           n = angular velocity / (2*pi)
*/
int powerF(double m, double n) {
  int magicNumber = 9550;
  double pwr, pawn;

  pawn = m * n;
  pwr = pawn / magicNumber;

  return pwr;
}
